apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: /propagate-values
  name: propagate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|default|propagate-values'
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.name
- source:
    kind: ConfigMap
    name: azure-context
    fieldPath: data.subscription-id
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.subscription-id
- source:
    kind: ConfigMap
    name: azure-context
    fieldPath: data.client-id
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.client-id
- source:
    kind: ConfigMap
    name: azure-context
    fieldPath: data.client-secret
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.client-secret
- source:
    kind: ConfigMap
    name: azure-context
    fieldPath: data.tenant-id
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.tenant-id
- source:
    kind: ConfigMap
    name: azure-context
    fieldPath: data.location
  targets:
  - select:
      kind: ConfigMap
      name: setters
    fieldPaths:
    - data.location
