apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata: # kpt-merge: default/example
  name: example
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'cluster.x-k8s.io|Cluster|default|example'
    nephio.org/cluster-name: example
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: example
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: example
